### ISSUE TITLE
preg_replace issue

### ISSUE THREAD

**Issue by radog** [phoboslab/Asaph#3]
Hi,

how to remove issue:

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /public/lib/db.php on line 60

in server with PHP 5.5.5

Thank you

**Comment by phoboslab** [comment]
See https://github.com/phoboslab/picturelicious/issues/5#issuecomment-112734078 - same issue, different repo.

Changing it would require PHP 5.3; this deprication message can also safely be ignored for now.

**Comment by radog** [comment]
Thnak you!!!!! Work fine :-)
